In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import warnings
from collections import Counter
import itertools
warnings.filterwarnings('ignore')

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from xgboost import XGBClassifier
import lightgbm as lgb
!pip install catboost
from catboost import CatBoostClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 9.1 MB/s eta 0:00:00


#Model Definition

In [4]:
class Models:

  def __inint__(self, X_train, y_train, y_test, X_test):
    self.X_train = X_train
    self.y_train = y_train
    self.y_test = y_test
    self.X_test = X_test


  def LR(self, X_train, y_train, y_test, X_test):
    # Create a logistic regression object
    clf = LogisticRegression(random_state=0)
    # Train the model on the training data
    clf.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = clf.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def GNB(self, X_train, y_train, y_test, X_test):
    gnb = GaussianNB()
    gnb.fit(X_train, y_train)
    y_pred = gnb.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)
    return gnb

  def DT(self, X_train, y_train, y_test, X_test):
    dt = DecisionTreeClassifier(random_state=0)
    dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def RF(self, X_train, y_train, y_test, X_test):
    rfc = RandomForestClassifier(n_estimators=100, random_state=0)
    rfc.fit(X_train, y_train)
    y_pred = rfc.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def SVC(self, X_train, y_train, y_test, X_test):
    # Create an SVM object
    svc = SVC(random_state=0)
    svc.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = svc.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def KNN(self, X_train, y_train, y_test, X_test):
    # Create a KNN object
    knn = KNeighborsClassifier()
    knn.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = knn.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)


  def GB(self, X_train, y_train, y_test, X_test):
    # Create a Gradient Boosting object
    gb = GradientBoostingClassifier(random_state=0)
    gb.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = gb.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def ADAB(self, X_train, y_train, y_test, X_test):
    # Create an AdaBoost object
    ada = AdaBoostClassifier(random_state=0)
    ada.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = ada.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def BAG(self, X_train, y_train, y_test, X_test):
    # Create a Bagging object
    tree = DecisionTreeClassifier(random_state=0)
    bag = BaggingClassifier(tree, random_state=0)
    bag.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = bag.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def XGB(self, X_train, y_train, y_test, X_test):
    xgb = XGBClassifier(random_state=0)
    xgb.fit(X_train, y_train)
    y_pred = xgb.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def LGB(self, X_train, y_train, y_test, X_test):
    # Create a LightGBM object
    lgbm = lgb.LGBMClassifier(random_state=0)
    lgbm.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = lgbm.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def CB(self, X_train, y_train, y_test, X_test):
    cat = CatBoostClassifier(random_state=0, verbose=0)
    cat.fit(X_train, y_train)

    #Predict the classes of the testing data
    y_pred = cat.predict(X_test)
    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def LDA(self, X_train, y_train, y_test, X_test):
    # Create a LinearDiscriminantAnalysis object and fit the model to the training data
    lda = LinearDiscriminantAnalysis()
    lda.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = lda.predict(X_test)

    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)
    return lda

  def QDA(self, X_train, y_train, y_test, X_test):
    #Create a QuadraticDiscriminantAnalysis object
    qda = QuadraticDiscriminantAnalysis()
    #Train the model on the training data
    qda.fit(X_train, y_train)

    #Predict the classes of the testing data
    y_pred = qda.predict(X_test)
    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)


    return qda


In [5]:
#Making object of the class Models
model = Models()

#Tuning

In [6]:
class Model_tuning:

  def __inint__(self, X_train, y_train, y_test, X_test):
    self.X_train = X_train
    self.y_train = y_train
    self.y_test = y_test
    self.X_test = X_test

  def LR_t(self, X_train, y_train, y_test, X_test):
    param_grid = {'C': [0.01, 0.1, 1.0, 10.0, 100.0], 'penalty': ['l1', 'l2']}
    LR_t = LogisticRegression(random_state=0)
    #Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(LR_t, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)  
    #Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    LR_t = LogisticRegression(**best_params, random_state=0)
    LR_t.fit(X_train, y_train)
    #Predict the classes of the testing data
    y_pred = LR_t.predict(X_test)

    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("#######################################################################")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("#######################################################################")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return LR_t

  def GNB_t(self, X_train, y_train, y_test, X_test):
    # Create a Gaussian Naive Bayes object
    gnb = GaussianNB()

    # Define the hyperparameter grid to search over
    param_grid = {'var_smoothing': np.logspace(0,-9, num=100)}

    # Create a GridSearchCV object and fit it to the training data
    gnb = GridSearchCV(gnb, param_grid, cv=10, scoring='accuracy')
    gnb.fit(X_train, y_train)

    #  Predict the classes of the testing data using the best estimator found by GridSearchCV
    y_pred = gnb.best_estimator_.predict(X_test)

    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return gnb

  def DT_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid
    param_grid = {'max_depth': [3, 5, 7, None], 
                  'min_samples_split': [2, 5, 10],
                  'min_samples_leaf': [1, 2, 4]}

    # Create a decision tree object
    dt = DecisionTreeClassifier(random_state=0)
    # Create a GridSearchCV object with 5-fold cross-validation
    dt_cv = GridSearchCV(dt, param_grid, cv=5)

    # Train the model on the training data
    dt_cv.fit(X_train, y_train)
    # Print the best parameters and best score
    print('Best Parameters:', dt_cv.best_params_)
    print('Best Score:', dt_cv.best_score_)
    # Predict the classes of the testing data using the best model
    y_pred = dt_cv.predict(X_test)

    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return dt_cv

  def RF_t(self, X_train, y_train, y_test, X_test):
    # Set the parameter grid for hyperparameter tuning
    param_grid = {
        'n_estimators': [100, 200, 300],
        'max_depth': [None, 5, 10],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'max_features': ['auto', 'sqrt']
    }
    # Create a random forest classifier object
    rfc = RandomForestClassifier(random_state=0)
    # Create a GridSearchCV object
    grid_search = GridSearchCV(estimator=rfc, param_grid=param_grid, cv=5)
    # Train the GridSearchCV object on the training data
    grid_search.fit(X_train, y_train)
    # Print the best parameters and best score
    print("Best Parameters: ", grid_search.best_params_)
    print("Best Score: ", grid_search.best_score_)
    # Predict the classes of the testing data using the best estimator from the GridSearchCV
    y_pred = grid_search.best_estimator_.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return grid_search

  def SVC_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf', 'poly', 'sigmoid'], 'gamma': ['scale', 'auto']}
    # Create an SVM object
    svc = SVC(random_state=0)
    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(svc, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    svc = SVC(**best_params, probability=True, random_state=0)
    svc.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = svc.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return svc

  def KNN_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_neighbors': [3, 5, 7, 9, 11], 'weights': ['uniform', 'distance']}

    # Create a KNN object
    knn = KNeighborsClassifier()

    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(knn, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)

    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    knn = KNeighborsClassifier(**best_params)
    knn.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = knn.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return knn


  def GB_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_estimators': [50, 100, 150], 'max_depth': [3, 5, 7], 'learning_rate': [0.01, 0.1, 1.0]}
    # Create a Gradient Boosting object
    gb = GradientBoostingClassifier(random_state=0)
    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(gb, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    gb = GradientBoostingClassifier(**best_params, random_state=0)
    gb.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = gb.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return gb

  def ADAB_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_estimators': [50, 100, 150], 'learning_rate': [0.01, 0.1, 1.0]}
    # Create an AdaBoost object
    ada = AdaBoostClassifier(random_state=0)

    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(ada, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    ada = AdaBoostClassifier(**best_params, random_state=0)
    ada.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = ada.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return ada

  def BAG_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_estimators': [50, 100, 150], 'max_samples': [0.5, 0.7, 1.0], 'max_features': [0.5, 0.7, 1.0]}
    # Create a Bagging object
    tree = DecisionTreeClassifier(random_state=0)
    bag = BaggingClassifier(tree, random_state=0)
    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(bag, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    bag = BaggingClassifier(tree, **best_params, random_state=0)
    bag.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = bag.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return bag

  def XGB_t(self, X_train, y_train, y_test, X_test):
    param_grid = {'n_estimators': [50, 100, 150], 'learning_rate': [0.01, 0.1, 1.0], 'max_depth': [3, 5, 7]}
    xgb = XGBClassifier(random_state=0)
    grid_search = GridSearchCV(xgb, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    best_params = grid_search.best_params_
    xgb = XGBClassifier(**best_params, random_state=0)
    xgb.fit(X_train, y_train)
    y_pred = xgb.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return xgb

  def LGB_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'num_leaves': [31, 63, 127], 'learning_rate': [0.1, 0.05, 0.01], 'n_estimators': [50, 100, 150]}

    # Create a LightGBM object
    lgbm = lgb.LGBMClassifier(random_state=0)

    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(lgbm, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    lgbm = lgb.LGBMClassifier(**best_params, random_state=0)
    lgbm.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = lgbm.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return lgbm

  def CB_t(self, X_train, y_train, y_test, X_test):
    #Define the parameter grid for GridSearchCV
    param_grid = {'learning_rate': [0.1, 0.05, 0.01], 'n_estimators': [50, 100, 150], 'depth': [4, 6, 8]}

    #Create a CatBoost object
    cat = CatBoostClassifier(random_state=0, verbose=0)
    #Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(cat, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)

    #Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    cat = CatBoostClassifier(**best_params, random_state=0, verbose=0)
    cat.fit(X_train, y_train)
    #Predict the classes of the testing data
    y_pred = cat.predict(X_test)

    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return cat

  def LDA_t():
    print("LDA has no Parameter Tuning")

  def QDA_t():
    print("QDA has no parameter tuning")


In [7]:
modelt = Model_tuning()

#importing CSV 

In [8]:
df = pd.read_excel('/content/drive/MyDrive/Dashborad_academics/prediction_dataset1.xlsx')

In [9]:
df.head()

Sr. No.  AM-I(70442101)Attempts  AM-I(70442101) ESE (70) Final  \
0        1                       1                             32   
1        2                       1                             29   
2        3                       1                             64   
3        4                       1                             53   
4        5                       1                             31   

   AM-I(70442101) ISE (30) Final  AM-I(70442101) ICA (25) Final  \
0                             28                             23   
1                             25                             19   
2                             30                             24   
3                             25                             22   
4                             25                             24   

   AM-I(70442101) Condol/ Grace Final  AM-I(70442101) Total (125) Final  \
0                                   0                                83   
1                                   0                                73   
2                                   0                               118   
3                                   0                               100   
4                                   0                                80   

  AM-I(70442101)Grade Final  AM-I(70442101) GP Final  \
0                         A                        8   
1                        B+                        7   
2                         O                       10   
3                         O                       10   
4                         A                        8   

   AM-I(70442101) EGP (Credits = 4) Final  ... Sem VII & VIII BE SGPA Final    \
0                                      32  ...                       8.142857   
1                                      28  ...                       8.244898   
2                                      40  ...                       9.142857   
3                                      40  ...                       9.224490   
4                                      32  ...                       9.265306   

   Sem VII & VIII BE Status Final   Sem VII & VIII BE Grade Final  \
0                             Pass                              A   
1                             Pass                              A   
2                             Pass                             A+   
3                             Pass                             A+   
4                             Pass                             A+   

   Grand Total (5000)      %   EGP  CGPA (Credits = 153) Status  Grade  \
0                3309  66.18  1212                  7.92   Pass      A   
1                3426  68.52  1228                  8.03   Pass      A   
2                3909  78.18  1380                  9.02   Pass     A+   
3                4003  80.06  1430                  9.35   Pass     A+   
4                4011  80.22  1424                  9.31   Pass     A+   

   Number of extra years required  
0                               0  
1                               0  
2                               0  
3                               0  
4                               0  

[5 rows x 509 columns]

#Distrubuting data semester wise to get predictions and suggestions semester wise

In [10]:

#semester wise distribution
sem3 = df.iloc[:,1:75]
sem4 = df.iloc[:,75:149]
sem34 = df.iloc[:,149:157]
sem5 = df.iloc[:,157:239]
sem6 = df.iloc[:,239:327]
sem56 = df.iloc[:,327:335]
sem7 = df.iloc[:,335:418]
sem8 = df.iloc[:,418:494]
sem78 = df.iloc[:,494:502]
grandtotal = df.iloc[:,502:508]

#Distributing data subject wise to get predictions and suggestions subject wise

In [11]:
#subject wise distribution
am1 = df.iloc[:,1:11]
dms = df.iloc[:,11:21]
acc = df.iloc[:,21:34]
dt = df.iloc[:,34:47]
cg = df.iloc[:,47:57]
vb = df.iloc[:,57:66]
sem_3 = df.iloc[:,66:75]
am2 = df.iloc[:,75:85]
toc = df.iloc[:,85:95]
mp = df.iloc[:,95:108]
dc = df.iloc[:,108:118]
ds = df.iloc[:,118:131]
oodp = df.iloc[:,131:140]
sem_4 = df.iloc[:,140:157]
osc = df.iloc[:,157:170]
cn = df.iloc[:,170:183]
sp = df.iloc[:,183:193]
daa = df.iloc[:,193:203]
co = df.iloc[:,203:213]
jp = df.iloc[:,213:222]
sl1 = df.iloc[:,222:230]
sem_5 = df.iloc[:,230:239]
dbe = df.iloc[:,239:252]
cc = df.iloc[:,252:262]
uos = df.iloc[:,262:272]
mc = df.iloc[:,272:282]
se = df.iloc[:,282:292]
c = df.iloc[:,292:301]
mpj = df.iloc[:,301:310]
sl2 = df.iloc[:310:318]
sem_6 = df.iloc[:,318:335]
aca = df.iloc[:,335:345]
dsys = df.iloc[:,345:355]
mds = df.iloc[:,355:368]
pp1 = df.iloc[:,368:377]
py = df.iloc[:,377:383]
vt = df.iloc[:,383:389]
el1 = df.iloc[:,389:399]
el2 = df.iloc[:,399:409]
sem_7 = df.iloc[:,409:418]
mis = df.iloc[:,418:428]
ics = df.iloc[:,428:441]
wt = df.iloc[:,441:450]
pp2 = df.iloc[:,450:459]
ost = df.iloc[:,459:465]
el3 = df.iloc[:,465:475]
el4 = df.iloc[:,475:485]
sem_8 = df.iloc[:,485:502]

In [12]:
def preprocess(df,target):
  # Split the data into input features (X) and target variable (y)
  X = df.drop(target, axis=1)  # Input features
  y = df[target]  # Target variable
  # Convert the target variable to numeric values using label encoding
  le = LabelEncoder()
  y = le.fit_transform(y)
  cat_cols = X.select_dtypes(include=['category','object']).columns.tolist()

  print(cat_cols)
  # Convert categorical features into numerical values using one-hot encoding
  categorical_cols = cat_cols
  ohe = OneHotEncoder(handle_unknown='ignore', sparse=False)
  X_cat = pd.DataFrame(ohe.fit_transform(X[categorical_cols]))
  X_cat.columns = ohe.get_feature_names_out(categorical_cols)
  X_num = X.drop(categorical_cols, axis=1)
  X = pd.concat([X_num, X_cat], axis=1)
  # Split data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
  print("Shape of training split: ", X_train.shape)
  print("Shape of test split: ", X_test.shape)

  return X_train, X_test, y_train, y_test

#Sem - 7


In [13]:
sem7.head()

ACA(70444101) Attempts  ACA(70444101) ESE (70) Final  \
0                       1                            38   
1                       1                            43   
2                       1                            43   
3                       1                            52   
4                       1                            41   

   ACA(70444101) ISE (30) Final  ACA(70444101) ICA (25) Final  \
0                            15                            22   
1                            24                            20   
2                            25                            21   
3                            25                            23   
4                            25                            24   

   ACA(70444101) Condol/ Grace Final  ACA(70444101) Total (125) Final  \
0                                  0                               75   
1                                  0                               87   
2                                  0                               89   
3                                  0                              100   
4                                  0                               90   

  ACA(70444101) Grade Final  ACA(70444101) GP Final  \
0                         A                       8   
1                         A                       8   
2                        A+                       9   
3                         O                      10   
4                        A+                       9   

   ACA(70444101) EGP (Credits = 3) Final ACA(70444101) Status Final  ...  \
0                                     24                          P  ...   
1                                     24                          P  ...   
2                                     27                          P  ...   
3                                     30                          P  ...   
4                                     27                          P  ...   

   Ele-II Status Final  Sem VII Fail in subjects (8)  \
0                    P                             0   
1                    P                             0   
2                    P                             0   
3                    P                             0   
4                    P                             0   

   Sem VII Pass in subjects (8)  Sem VII Total (850) Final  Sem VII % Final  \
0                             8                        587            69.06   
1                             8                        616            72.47   
2                             8                        694            81.65   
3                             8                        676            79.53   
4                             8                        690            81.18   

   Sem VII Condol/ Grace Final Sem VII EGP Final  \
0                            0               212   
1                            0               215   
2                            0               240   
3                            0               239   
4                            0               237   

   Sem VII SGPA (Credits = 25) Final  Sem VII Status Final Sem VII Grade Final  
0                               8.48                 Pass                    A  
1                               8.60                  Pass                  A+  
2                               9.60                 Pass                    O  
3                               9.56                 Pass                    O  
4                               9.48                 Pass                   A+  

[5 rows x 83 columns]

In [14]:
sem7.shape

(200, 83)

In [15]:
target = 'Sem VII Grade Final'

In [16]:
X_train, X_test, y_train, y_test = preprocess(sem7,target)

['ACA(70444101) Grade Final', 'ACA(70444101) Status Final', 'DSys(70444102) Grade Final', 'DSys(70444102) Status Final', 'MDS(70444103) Grade Final', 'MDS(70444103) Status Final', 'PP-I(70444104) Grade Final', 'PP-I(70444104) Status Final', 'Py(70444105) Grade Final', 'Py(70444105) Status Final', 'VT(70444106) Grade Final', 'VT(70444106) Status Final', 'Ele-I Grade Final', 'Ele-I Status Final', 'Ele-II Grade Final', 'Ele-II Status Final', 'Sem VII Status Final']
Shape of training split:  (160, 114)
Shape of test split:  (40, 114)


#Logistic Regression

In [17]:
model.LR(X_train,y_train,y_test,X_test)

Accuracy: 0.675
Confusion Matrix:
 [[ 4  3  0  1]
 [ 2 17  0  5]
 [ 0  0  1  0]
 [ 0  2  0  5]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.50      0.57         8
           1       0.77      0.71      0.74        24
           2       1.00      1.00      1.00         1
           3       0.45      0.71      0.56         7

    accuracy                           0.68        40
   macro avg       0.72      0.73      0.72        40
weighted avg       0.70      0.68      0.68        40



Tuning and fitting

In [18]:
modelt.LR_t(X_train,y_train,y_test,X_test)

Accuracy: 0.675
#######################################################################
Confusion Matrix:
 [[ 4  4  0  0]
 [ 2 19  0  3]
 [ 1  0  0  0]
 [ 0  3  0  4]]
#######################################################################
Classification Report:
               precision    recall  f1-score   support

           0       0.57      0.50      0.53         8
           1       0.73      0.79      0.76        24
           2       0.00      0.00      0.00         1
           3       0.57      0.57      0.57         7

    accuracy                           0.68        40
   macro avg       0.47      0.47      0.47        40
weighted avg       0.65      0.68      0.66        40



LogisticRegression(C=0.01, random_state=0)

#Gaussian Naive Bayes

In [19]:
model.GNB(X_train,y_train,y_test,X_test)

Accuracy: 0.775
Confusion Matrix:
 [[ 4  4  0  0]
 [ 1 20  0  3]
 [ 1  0  0  0]
 [ 0  0  0  7]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.50      0.57         8
           1       0.83      0.83      0.83        24
           2       0.00      0.00      0.00         1
           3       0.70      1.00      0.82         7

    accuracy                           0.78        40
   macro avg       0.55      0.58      0.56        40
weighted avg       0.76      0.78      0.76        40



GaussianNB()

Tuning and fitting

In [20]:
modelt.GNB_t(X_train,y_train,y_test,X_test)

Accuracy: 0.925
Confusion Matrix:
 [[ 7  1  0  0]
 [ 1 23  0  0]
 [ 0  0  1  0]
 [ 0  1  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.88      0.88         8
           1       0.92      0.96      0.94        24
           2       1.00      1.00      1.00         1
           3       1.00      0.86      0.92         7

    accuracy                           0.93        40
   macro avg       0.95      0.92      0.93        40
weighted avg       0.93      0.93      0.92        40



GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.3...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy')

#Decision Tree

In [ ]:
model.DT(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.DT_t(X_train,y_train,y_test,X_test)

Best Parameters: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score: 0.9875
Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'max_depth': [3, 5, 7, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

#Random Forest

In [ ]:
model.RF(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



Tuning and Fitting

In [ ]:
modelt.RF_t(X_train,y_train,y_test,X_test)

Best Parameters:  {'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 100}
Best Score:  0.95
Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=0),
             param_grid={'max_depth': [None, 5, 10],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]})

#Support Vector Classifier

In [ ]:
model.SVC(X_train,y_train,y_test,X_test)

Accuracy: 0.675
Confusion Matrix:
 [[ 8  5  0  0]
 [ 0 19  0  0]
 [ 2  0  0  0]
 [ 0  6  0  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.62      0.70        13
           1       0.63      1.00      0.78        19
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         6

    accuracy                           0.68        40
   macro avg       0.36      0.40      0.37        40
weighted avg       0.56      0.68      0.59        40



Tuning and fitting

In [ ]:
modelt.SVC_t(X_train,y_train,y_test,X_test)

Accuracy: 0.875
Confusion Matrix:
 [[11  1  1  0]
 [ 0 18  0  1]
 [ 0  0  2  0]
 [ 0  2  0  4]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.86      0.95      0.90        19
           3       0.67      1.00      0.80         2
           4       0.80      0.67      0.73         6

    accuracy                           0.88        40
   macro avg       0.83      0.87      0.84        40
weighted avg       0.89      0.88      0.87        40



SVC(C=0.1, gamma='auto', kernel='poly', probability=True, random_state=0)

#K - Nearrest Neighbours

In [ ]:
model.KNN(X_train,y_train,y_test,X_test)

Accuracy: 0.9
Confusion Matrix:
 [[10  2  1  0]
 [ 0 18  0  1]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.77      0.87        13
           1       0.90      0.95      0.92        19
           3       0.67      1.00      0.80         2
           4       0.86      1.00      0.92         6

    accuracy                           0.90        40
   macro avg       0.86      0.93      0.88        40
weighted avg       0.91      0.90      0.90        40



Tuning and fitting

In [ ]:
modelt.KNN_t(X_train,y_train,y_test,X_test)

Accuracy: 0.875
Confusion Matrix:
 [[ 9  2  2  0]
 [ 0 18  0  1]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.69      0.82        13
           1       0.90      0.95      0.92        19
           3       0.50      1.00      0.67         2
           4       0.86      1.00      0.92         6

    accuracy                           0.88        40
   macro avg       0.81      0.91      0.83        40
weighted avg       0.91      0.88      0.88        40



KNeighborsClassifier(n_neighbors=9)

#Gradient Boosting

In [ ]:
model.GB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.GB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GradientBoostingClassifier(learning_rate=0.01, n_estimators=50, random_state=0)

#AdaBoost

In [ ]:
model.ADAB(X_train,y_train,y_test,X_test)

Accuracy: 0.95
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 2  0  0  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       0.87      1.00      0.93        13
           1       1.00      1.00      1.00        19
           3       0.00      0.00      0.00         2
           4       1.00      1.00      1.00         6

    accuracy                           0.95        40
   macro avg       0.72      0.75      0.73        40
weighted avg       0.91      0.95      0.93        40



tuning and fitting

In [ ]:
modelt.ADAB_t(X_train,y_train,y_test,X_test)

Accuracy: 0.85
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  6  0  0]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.76      1.00      0.86        19
           3       1.00      1.00      1.00         2
           4       0.00      0.00      0.00         6

    accuracy                           0.85        40
   macro avg       0.69      0.75      0.72        40
weighted avg       0.74      0.85      0.79        40



AdaBoostClassifier(learning_rate=0.1, random_state=0)

#Bagging

In [ ]:
model.BAG(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.BAG_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



BaggingClassifier(estimator=DecisionTreeClassifier(random_state=0),
                  max_features=0.5, max_samples=0.5, n_estimators=150,
                  random_state=0)

#XGBoost

In [ ]:
model.XGB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.XGB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=50, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

#LightGBM

In [ ]:
model.LGB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.LGB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



LGBMClassifier(n_estimators=50, random_state=0)

#CATBoost

In [ ]:
model.CB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.CB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



#Linear Discriminant Analysis

In [ ]:
model.LDA(X_train,y_train,y_test,X_test)

Accuracy: 0.75
Confusion Matrix:
 [[ 7  3  3  0]
 [ 0 17  0  2]
 [ 0  0  2  0]
 [ 0  2  0  4]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.54      0.70        13
           1       0.77      0.89      0.83        19
           3       0.40      1.00      0.57         2
           4       0.67      0.67      0.67         6

    accuracy                           0.75        40
   macro avg       0.71      0.77      0.69        40
weighted avg       0.81      0.75      0.75        40



LinearDiscriminantAnalysis()

#Quadratic discriminant Analysis

In [ ]:
model.QDA(X_train,y_train,y_test,X_test)

ValueError: ignored

#========================================================

#Sem - 7 total


In [21]:
sem_7.head()

Sem VII Fail in subjects (8)  Sem VII Pass in subjects (8)  \
0                             0                             8   
1                             0                             8   
2                             0                             8   
3                             0                             8   
4                             0                             8   

   Sem VII Total (850) Final  Sem VII % Final  Sem VII Condol/ Grace Final  \
0                        587            69.06                            0   
1                        616            72.47                            0   
2                        694            81.65                            0   
3                        676            79.53                            0   
4                        690            81.18                            0   

   Sem VII EGP Final  Sem VII SGPA (Credits = 25) Final Sem VII Status Final  \
0                212                               8.48                Pass    
1                215                               8.60                 Pass   
2                240                               9.60                Pass    
3                239                               9.56                Pass    
4                237                               9.48                Pass    

  Sem VII Grade Final  
0                   A  
1                  A+  
2                   O  
3                   O  
4                  A+

In [22]:
sem_7.shape

(200, 9)

In [23]:
target = 'Sem VII Grade Final'

In [24]:
X_train, X_test, y_train, y_test = preprocess(sem_7,target)

['Sem VII Status Final']
Shape of training split:  (160, 10)
Shape of test split:  (40, 10)


#Logistic Regression

In [25]:
model.LR(X_train,y_train,y_test,X_test)

Accuracy: 0.75
Confusion Matrix:
 [[ 4  4  0  0]
 [ 1 23  0  0]
 [ 1  0  0  0]
 [ 0  4  0  3]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.50      0.57         8
           1       0.74      0.96      0.84        24
           2       0.00      0.00      0.00         1
           3       1.00      0.43      0.60         7

    accuracy                           0.75        40
   macro avg       0.60      0.47      0.50        40
weighted avg       0.75      0.75      0.72        40



Tuning and fitting

In [26]:
modelt.LR_t(X_train,y_train,y_test,X_test)

Accuracy: 0.725
#######################################################################
Confusion Matrix:
 [[ 6  2  0  0]
 [ 2 20  0  2]
 [ 1  0  0  0]
 [ 0  4  0  3]]
#######################################################################
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.75      0.71         8
           1       0.77      0.83      0.80        24
           2       0.00      0.00      0.00         1
           3       0.60      0.43      0.50         7

    accuracy                           0.73        40
   macro avg       0.51      0.50      0.50        40
weighted avg       0.70      0.72      0.71        40



LogisticRegression(C=100.0, random_state=0)

#Gaussian Naive Bayes

In [27]:
model.GNB(X_train,y_train,y_test,X_test)

Accuracy: 0.825
Confusion Matrix:
 [[ 7  1  0  0]
 [ 1 18  0  5]
 [ 0  0  1  0]
 [ 0  0  0  7]]
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.88      0.88         8
           1       0.95      0.75      0.84        24
           2       1.00      1.00      1.00         1
           3       0.58      1.00      0.74         7

    accuracy                           0.82        40
   macro avg       0.85      0.91      0.86        40
weighted avg       0.87      0.82      0.83        40



GaussianNB()

Tuning and fitting

In [ ]:
modelt.GNB_t(X_train,y_train,y_test,X_test)

Accuracy: 0.875
Confusion Matrix:
 [[ 9  2  2  0]
 [ 0 18  0  1]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.69      0.82        13
           1       0.90      0.95      0.92        19
           3       0.50      1.00      0.67         2
           4       0.86      1.00      0.92         6

    accuracy                           0.88        40
   macro avg       0.81      0.91      0.83        40
weighted avg       0.91      0.88      0.88        40



GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.3...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy')

#Decision Tree

In [ ]:
model.DT(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.DT_t(X_train,y_train,y_test,X_test)

Best Parameters: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score: 0.9875
Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'max_depth': [3, 5, 7, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

#Random Forest

In [ ]:
model.RF(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



Tuning and Fitting

In [ ]:
modelt.RF_t(X_train,y_train,y_test,X_test)

#Support Vector Classifier

In [ ]:
model.SVC(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.SVC_t(X_train,y_train,y_test,X_test)

#K - Nearrest Neighbours

In [ ]:
model.KNN(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.KNN_t(X_train,y_train,y_test,X_test)

#Gradient Boosting

In [ ]:
model.GB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.GB_t(X_train,y_train,y_test,X_test)

#AdaBoost

In [ ]:
model.ADAB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.ADAB_t(X_train,y_train,y_test,X_test)

#Bagging

In [ ]:
model.BAG(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.BAG_t(X_train,y_train,y_test,X_test)

#XGBoost

In [ ]:
model.XGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.XGB_t(X_train,y_train,y_test,X_test)

#LightGBM

In [ ]:
model.LGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.LGB_t(X_train,y_train,y_test,X_test)

#CATBoost

In [ ]:
model.CB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.CB_t(X_train,y_train,y_test,X_test)

#Linear Discriminant Analysis

In [ ]:
model.LDA(X_train,y_train,y_test,X_test)

#Quadratic discriminant Analysis

In [ ]:
model.QDA(X_train,y_train,y_test,X_test)

#========================================================

#Sem - 8


In [28]:
sem8.head()

MIS(70444201) Attempts  MIS(70444201) ESE (70) Final  \
0                       1                            40   
1                       1                            47   
2                       1                            39   
3                       1                            55   
4                       1                            55   

   MIS(70444201) ISE (30) Final  MIS(70444201) ICA (25) Final  \
0                            24                            22   
1                            26                            21   
2                            29                            24   
3                            24                            23   
4                            29                            24   

   MIS(70444201) Condol/ Grace Final  MIS(70444201) Total (125) Final  \
0                                  0                               86   
1                                  0                               94   
2                                  0                               92   
3                                  0                              102   
4                                  0                              108   

  MIS(70444201) Grade Final  MIS(70444201) GP Final  \
0                         A                       8   
1                        A+                       9   
2                        A+                       9   
3                         O                      10   
4                         O                      10   

   MIS(70444201) EGP (Credits = 3) Final MIS(70444201) Status Final  ...  \
0                                     24                          P  ...   
1                                     27                          P  ...   
2                                     27                          P  ...   
3                                     30                          P  ...   
4                                     30                          P  ...   

   Ele-IV Status Final  Sem VIII Fail in subjects (6)  \
0                    P                              0   
1                    P                              0   
2                    P                              0   
3                    P                              0   
4                    P                              0   

   Sem VIII Pass in subjects (6)  Sem VIII Total (850) Final  \
0                              7                         622   
1                              7                         643   
2                              7                         698   
3                              7                         718   
4                              7                         734   

   Sem VIII % Final  Sem VIII Condol/ Grace Final  Sem VIII EGP Final   \
0             73.18                             0                  187   
1             75.65                             0                  189   
2             82.12                             0                  208   
3             84.47                             0                  213   
4             86.35                             0                  217   

   Sem VIII SGPA (Credits = 22) Final   Sem VIII Status Final   \
0                             8.500000                    Pass   
1                             8.590909                    Pass   
2                             9.454545                    Pass   
3                             9.681818                    Pass   
4                             9.863636                    Pass   

  Sem VIII Grade Final  
0                   A+  
1                   A+  
2                   A+  
3                    O  
4                    O  

[5 rows x 76 columns]

In [29]:
sem8.shape

(200, 76)

In [30]:
target = 'Sem VIII Grade Final'

In [31]:
X_train, X_test, y_train, y_test = preprocess(sem8,target)

['MIS(70444201) Grade Final', 'MIS(70444201) Status Final', 'ICS(70444202) Grade Final', 'ICS(70444202) Status Final', 'WT(70444203) Grade Final', 'WT(70444203) Status Final', 'PP-II(70444204) Grade Final', 'PP-II(70444204) Status Final', 'OST(70444105) Grade Final', 'OST(70444105) Status Final', 'Ele-III Grade Final', 'Ele-III Status Final', 'Ele-IV Grade Final', 'Ele-IV Status Final', 'Sem VIII Status Final ']
Shape of training split:  (160, 97)
Shape of test split:  (40, 97)


#Logistic Regression

In [32]:
model.LR(X_train,y_train,y_test,X_test)

Accuracy: 0.8
Confusion Matrix:
 [[ 1  3  0]
 [ 2 21  2]
 [ 0  1 10]]
Classification Report:
               precision    recall  f1-score   support

           0       0.33      0.25      0.29         4
           1       0.84      0.84      0.84        25
           2       0.83      0.91      0.87        11

    accuracy                           0.80        40
   macro avg       0.67      0.67      0.67        40
weighted avg       0.79      0.80      0.79        40



Tuning and fitting

In [33]:
modelt.LR_t(X_train,y_train,y_test,X_test)

Accuracy: 0.8
#######################################################################
Confusion Matrix:
 [[ 1  3  0]
 [ 1 22  2]
 [ 0  2  9]]
#######################################################################
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.25      0.33         4
           1       0.81      0.88      0.85        25
           2       0.82      0.82      0.82        11

    accuracy                           0.80        40
   macro avg       0.71      0.65      0.67        40
weighted avg       0.78      0.80      0.79        40



LogisticRegression(C=0.01, random_state=0)

#Gaussian Naive Bayes

In [34]:
model.GNB(X_train,y_train,y_test,X_test)

Accuracy: 0.775
Confusion Matrix:
 [[ 4  0  0]
 [ 3 16  6]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       0.57      1.00      0.73         4
           1       1.00      0.64      0.78        25
           2       0.65      1.00      0.79        11

    accuracy                           0.78        40
   macro avg       0.74      0.88      0.76        40
weighted avg       0.86      0.78      0.78        40



GaussianNB()

Tuning and fitting

In [ ]:
modelt.GNB_t(X_train,y_train,y_test,X_test)

Accuracy: 0.875
Confusion Matrix:
 [[11  1  1  0]
 [ 0 16  0  3]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.94      0.84      0.89        19
           3       0.67      1.00      0.80         2
           4       0.67      1.00      0.80         6

    accuracy                           0.88        40
   macro avg       0.82      0.92      0.85        40
weighted avg       0.91      0.88      0.88        40



GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.3...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy')

#Decision Tree

In [ ]:
model.DT(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.DT_t(X_train,y_train,y_test,X_test)

Best Parameters: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score: 0.9875
Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'max_depth': [3, 5, 7, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

#Random Forest

In [ ]:
model.RF(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



Tuning and Fitting

In [ ]:
modelt.RF_t(X_train,y_train,y_test,X_test)

#Support Vector Classifier

In [ ]:
model.SVC(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.SVC_t(X_train,y_train,y_test,X_test)

#K - Nearrest Neighbours

In [ ]:
model.KNN(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.KNN_t(X_train,y_train,y_test,X_test)

#Gradient Boosting

In [ ]:
model.GB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.GB_t(X_train,y_train,y_test,X_test)

#AdaBoost

In [ ]:
model.ADAB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.ADAB_t(X_train,y_train,y_test,X_test)

#Bagging

In [ ]:
model.BAG(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.BAG_t(X_train,y_train,y_test,X_test)

#XGBoost

In [ ]:
model.XGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.XGB_t(X_train,y_train,y_test,X_test)

#LightGBM

In [ ]:
model.LGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.LGB_t(X_train,y_train,y_test,X_test)

#CATBoost

In [ ]:
model.CB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.CB_t(X_train,y_train,y_test,X_test)

#Linear Discriminant Analysis

In [ ]:
model.LDA(X_train,y_train,y_test,X_test)

#Quadratic discriminant Analysis

In [ ]:
model.QDA(X_train,y_train,y_test,X_test)

#========================================================

#Sem - 8 total


In [35]:
sem_8.head()

Sem VIII Fail in subjects (6)  Sem VIII Pass in subjects (6)  \
0                              0                              7   
1                              0                              7   
2                              0                              7   
3                              0                              7   
4                              0                              7   

   Sem VIII Total (850) Final  Sem VIII % Final  Sem VIII Condol/ Grace Final  \
0                         622             73.18                             0   
1                         643             75.65                             0   
2                         698             82.12                             0   
3                         718             84.47                             0   
4                         734             86.35                             0   

   Sem VIII EGP Final   Sem VIII SGPA (Credits = 22) Final   \
0                  187                             8.500000   
1                  189                             8.590909   
2                  208                             9.454545   
3                  213                             9.681818   
4                  217                             9.863636   

  Sem VIII Status Final  Sem VIII Grade Final  \
0                   Pass                   A+   
1                   Pass                   A+   
2                   Pass                   A+   
3                   Pass                    O   
4                   Pass                    O   

   Sem VII & VIII Grand Total (1650) Final  \
0                                     1209   
1                                     1259   
2                                     1392   
3                                     1394   
4                                     1424   

   Sem VII & VIII Condol/ Grace Final  \
0                                   0   
1                                   0   
2                                   0   
3                                   0   
4                                   0   

   Sem VII & VIII Grand Total with Condol/ Grace (1700) Final  \
0                                               1209            
1                                               1259            
2                                               1392            
3                                               1394            
4                                               1424            

   Sem VII & VIII % Final  Sem VII & VIII  BE EGP (Credits =49) Final   \
0                   71.12                                          399   
1                   76.30                                          404   
2                   81.88                                          448   
3                   82.00                                          452   
4                   83.76                                          454   

   Sem VII & VIII BE SGPA Final   Sem VII & VIII BE Status Final   \
0                        8.142857                            Pass   
1                        8.244898                            Pass   
2                        9.142857                            Pass   
3                        9.224490                            Pass   
4                        9.265306                            Pass   

  Sem VII & VIII BE Grade Final  
0                             A  
1                             A  
2                            A+  
3                            A+  
4                            A+

In [36]:
sem_8.shape

(200, 17)

In [37]:
target = 'Sem VIII Grade Final'

In [38]:
X_train, X_test, y_train, y_test = preprocess(sem_8,target)

['Sem VIII Status Final ', 'Sem VII & VIII BE Status Final ', 'Sem VII & VIII BE Grade Final']
Shape of training split:  (160, 19)
Shape of test split:  (40, 19)


#Logistic Regression

In [39]:
model.LR(X_train,y_train,y_test,X_test)

Accuracy: 0.7
Confusion Matrix:
 [[ 0  4  0]
 [ 0 25  0]
 [ 0  8  3]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.68      1.00      0.81        25
           2       1.00      0.27      0.43        11

    accuracy                           0.70        40
   macro avg       0.56      0.42      0.41        40
weighted avg       0.70      0.70      0.62        40



Tuning and fitting

In [40]:
modelt.LR_t(X_train,y_train,y_test,X_test)

Accuracy: 0.725
#######################################################################
Confusion Matrix:
 [[ 0  4  0]
 [ 0 25  0]
 [ 0  7  4]]
#######################################################################
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.69      1.00      0.82        25
           2       1.00      0.36      0.53        11

    accuracy                           0.73        40
   macro avg       0.56      0.45      0.45        40
weighted avg       0.71      0.72      0.66        40



LogisticRegression(C=0.01, random_state=0)

#Gaussian Naive Bayes

In [41]:
model.GNB(X_train,y_train,y_test,X_test)

Accuracy: 0.95
Confusion Matrix:
 [[ 4  0  0]
 [ 0 23  2]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      0.92      0.96        25
           2       0.85      1.00      0.92        11

    accuracy                           0.95        40
   macro avg       0.95      0.97      0.96        40
weighted avg       0.96      0.95      0.95        40



GaussianNB()

Tuning and fitting

In [ ]:
modelt.GNB_t(X_train,y_train,y_test,X_test)

Accuracy: 0.875
Confusion Matrix:
 [[11  1  1  0]
 [ 0 16  0  3]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.94      0.84      0.89        19
           3       0.67      1.00      0.80         2
           4       0.67      1.00      0.80         6

    accuracy                           0.88        40
   macro avg       0.82      0.92      0.85        40
weighted avg       0.91      0.88      0.88        40



GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.3...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy')

#Decision Tree

In [ ]:
model.DT(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.DT_t(X_train,y_train,y_test,X_test)

Best Parameters: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score: 0.9875
Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'max_depth': [3, 5, 7, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

#Random Forest

In [ ]:
model.RF(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



Tuning and Fitting

In [ ]:
modelt.RF_t(X_train,y_train,y_test,X_test)

#Support Vector Classifier

In [ ]:
model.SVC(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.SVC_t(X_train,y_train,y_test,X_test)

#K - Nearrest Neighbours

In [ ]:
model.KNN(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.KNN_t(X_train,y_train,y_test,X_test)

#Gradient Boosting

In [ ]:
model.GB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.GB_t(X_train,y_train,y_test,X_test)

#AdaBoost

In [ ]:
model.ADAB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.ADAB_t(X_train,y_train,y_test,X_test)

#Bagging

In [ ]:
model.BAG(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.BAG_t(X_train,y_train,y_test,X_test)

#XGBoost

In [ ]:
model.XGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.XGB_t(X_train,y_train,y_test,X_test)

#LightGBM

In [ ]:
model.LGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.LGB_t(X_train,y_train,y_test,X_test)

#CATBoost

In [ ]:
model.CB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.CB_t(X_train,y_train,y_test,X_test)

#Linear Discriminant Analysis

In [ ]:
model.LDA(X_train,y_train,y_test,X_test)

#Quadratic discriminant Analysis

In [ ]:
model.QDA(X_train,y_train,y_test,X_test)

#========================================================

#Sem - 7 and 8 Cummulative


In [42]:
sem78.head()

Sem VII & VIII Grand Total (1650) Final  \
0                                     1209   
1                                     1259   
2                                     1392   
3                                     1394   
4                                     1424   

   Sem VII & VIII Condol/ Grace Final  \
0                                   0   
1                                   0   
2                                   0   
3                                   0   
4                                   0   

   Sem VII & VIII Grand Total with Condol/ Grace (1700) Final  \
0                                               1209            
1                                               1259            
2                                               1392            
3                                               1394            
4                                               1424            

   Sem VII & VIII % Final  Sem VII & VIII  BE EGP (Credits =49) Final   \
0                   71.12                                          399   
1                   76.30                                          404   
2                   81.88                                          448   
3                   82.00                                          452   
4                   83.76                                          454   

   Sem VII & VIII BE SGPA Final   Sem VII & VIII BE Status Final   \
0                        8.142857                            Pass   
1                        8.244898                            Pass   
2                        9.142857                            Pass   
3                        9.224490                            Pass   
4                        9.265306                            Pass   

  Sem VII & VIII BE Grade Final  
0                             A  
1                             A  
2                            A+  
3                            A+  
4                            A+

In [43]:
sem78.shape

(200, 8)

In [46]:
target = 'Sem VII & VIII BE Grade Final'

In [47]:
X_train, X_test, y_train, y_test = preprocess(sem78,target)

['Sem VII & VIII BE Status Final ']
Shape of training split:  (160, 7)
Shape of test split:  (40, 7)


#Logistic Regression

In [48]:
model.LR(X_train,y_train,y_test,X_test)

Accuracy: 0.75
Confusion Matrix:
 [[ 5  5  0  0]
 [ 3 24  0  1]
 [ 0  1  0  0]
 [ 0  0  0  1]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.50      0.56        10
           1       0.80      0.86      0.83        28
           2       0.00      0.00      0.00         1
           3       0.50      1.00      0.67         1

    accuracy                           0.75        40
   macro avg       0.48      0.59      0.51        40
weighted avg       0.73      0.75      0.73        40



Tuning and fitting

In [49]:
modelt.LR_t(X_train,y_train,y_test,X_test)

Accuracy: 0.75
#######################################################################
Confusion Matrix:
 [[ 5  5  0  0]
 [ 3 24  0  1]
 [ 0  1  0  0]
 [ 0  0  0  1]]
#######################################################################
Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.50      0.56        10
           1       0.80      0.86      0.83        28
           2       0.00      0.00      0.00         1
           3       0.50      1.00      0.67         1

    accuracy                           0.75        40
   macro avg       0.48      0.59      0.51        40
weighted avg       0.73      0.75      0.73        40



LogisticRegression(random_state=0)

#Gaussian Naive Bayes

In [50]:
model.GNB(X_train,y_train,y_test,X_test)

Accuracy: 0.85
Confusion Matrix:
 [[ 8  0  2  0]
 [ 3 24  0  1]
 [ 0  0  1  0]
 [ 0  0  0  1]]
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.80      0.76        10
           1       1.00      0.86      0.92        28
           2       0.33      1.00      0.50         1
           3       0.50      1.00      0.67         1

    accuracy                           0.85        40
   macro avg       0.64      0.91      0.71        40
weighted avg       0.90      0.85      0.87        40



GaussianNB()

Tuning and fitting

In [ ]:
modelt.GNB_t(X_train,y_train,y_test,X_test)

Accuracy: 0.875
Confusion Matrix:
 [[11  1  1  0]
 [ 0 16  0  3]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.94      0.84      0.89        19
           3       0.67      1.00      0.80         2
           4       0.67      1.00      0.80         6

    accuracy                           0.88        40
   macro avg       0.82      0.92      0.85        40
weighted avg       0.91      0.88      0.88        40



GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.3...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy')

#Decision Tree

In [ ]:
model.DT(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [ ]:
modelt.DT_t(X_train,y_train,y_test,X_test)

Best Parameters: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score: 0.9875
Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'max_depth': [3, 5, 7, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

#Random Forest

In [ ]:
model.RF(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[13  0  0  0]
 [ 0 19  0  0]
 [ 0  0  2  0]
 [ 0  0  0  6]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        19
           3       1.00      1.00      1.00         2
           4       1.00      1.00      1.00         6

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



Tuning and Fitting

In [ ]:
modelt.RF_t(X_train,y_train,y_test,X_test)

#Support Vector Classifier

In [ ]:
model.SVC(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.SVC_t(X_train,y_train,y_test,X_test)

#K - Nearrest Neighbours

In [ ]:
model.KNN(X_train,y_train,y_test,X_test)

Tuning and fitting

In [ ]:
modelt.KNN_t(X_train,y_train,y_test,X_test)

#Gradient Boosting

In [ ]:
model.GB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.GB_t(X_train,y_train,y_test,X_test)

#AdaBoost

In [ ]:
model.ADAB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.ADAB_t(X_train,y_train,y_test,X_test)

#Bagging

In [ ]:
model.BAG(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.BAG_t(X_train,y_train,y_test,X_test)

#XGBoost

In [ ]:
model.XGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.XGB_t(X_train,y_train,y_test,X_test)

#LightGBM

In [ ]:
model.LGB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.LGB_t(X_train,y_train,y_test,X_test)

#CATBoost

In [ ]:
model.CB(X_train,y_train,y_test,X_test)

tuning and fitting

In [ ]:
modelt.CB_t(X_train,y_train,y_test,X_test)

#Linear Discriminant Analysis

In [ ]:
model.LDA(X_train,y_train,y_test,X_test)

#Quadratic discriminant Analysis

In [ ]:
model.QDA(X_train,y_train,y_test,X_test)

#========================================================