In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import warnings
from collections import Counter
import itertools
warnings.filterwarnings('ignore')

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from xgboost import XGBClassifier
import lightgbm as lgb
!pip install catboost
from catboost import CatBoostClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 9.1 MB/s eta 0:00:00


#Model Definition

In [4]:
class Models:

  def __inint__(self, X_train, y_train, y_test, X_test):
    self.X_train = X_train
    self.y_train = y_train
    self.y_test = y_test
    self.X_test = X_test


  def LR(self, X_train, y_train, y_test, X_test):
    # Create a logistic regression object
    clf = LogisticRegression(random_state=0)
    # Train the model on the training data
    clf.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = clf.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def GNB(self, X_train, y_train, y_test, X_test):
    gnb = GaussianNB()
    gnb.fit(X_train, y_train)
    y_pred = gnb.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)
    return gnb

  def DT(self, X_train, y_train, y_test, X_test):
    dt = DecisionTreeClassifier(random_state=0)
    dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def RF(self, X_train, y_train, y_test, X_test):
    rfc = RandomForestClassifier(n_estimators=100, random_state=0)
    rfc.fit(X_train, y_train)
    y_pred = rfc.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def SVC(self, X_train, y_train, y_test, X_test):
    # Create an SVM object
    svc = SVC(random_state=0)
    svc.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = svc.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def KNN(self, X_train, y_train, y_test, X_test):
    # Create a KNN object
    knn = KNeighborsClassifier()
    knn.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = knn.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)


  def GB(self, X_train, y_train, y_test, X_test):
    # Create a Gradient Boosting object
    gb = GradientBoostingClassifier(random_state=0)
    gb.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = gb.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def ADAB(self, X_train, y_train, y_test, X_test):
    # Create an AdaBoost object
    ada = AdaBoostClassifier(random_state=0)
    ada.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = ada.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def BAG(self, X_train, y_train, y_test, X_test):
    # Create a Bagging object
    tree = DecisionTreeClassifier(random_state=0)
    bag = BaggingClassifier(tree, random_state=0)
    bag.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = bag.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def XGB(self, X_train, y_train, y_test, X_test):
    xgb = XGBClassifier(random_state=0)
    xgb.fit(X_train, y_train)
    y_pred = xgb.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def LGB(self, X_train, y_train, y_test, X_test):
    # Create a LightGBM object
    lgbm = lgb.LGBMClassifier(random_state=0)
    lgbm.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = lgbm.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def CB(self, X_train, y_train, y_test, X_test):
    cat = CatBoostClassifier(random_state=0, verbose=0)
    cat.fit(X_train, y_train)

    #Predict the classes of the testing data
    y_pred = cat.predict(X_test)
    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

  def LDA(self, X_train, y_train, y_test, X_test):
    # Create a LinearDiscriminantAnalysis object and fit the model to the training data
    lda = LinearDiscriminantAnalysis()
    lda.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = lda.predict(X_test)

    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)
    return lda

  def QDA(self, X_train, y_train, y_test, X_test):
    #Create a QuadraticDiscriminantAnalysis object
    qda = QuadraticDiscriminantAnalysis()
    #Train the model on the training data
    qda.fit(X_train, y_train)

    #Predict the classes of the testing data
    y_pred = qda.predict(X_test)
    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)


    return qda


In [5]:
#Making object of the class Models
model = Models()

#Tuning

In [6]:
class Model_tuning:

  def __inint__(self, X_train, y_train, y_test, X_test):
    self.X_train = X_train
    self.y_train = y_train
    self.y_test = y_test
    self.X_test = X_test

  def LR_t(self, X_train, y_train, y_test, X_test):
    param_grid = {'C': [0.01, 0.1, 1.0, 10.0, 100.0], 'penalty': ['l1', 'l2']}
    LR_t = LogisticRegression(random_state=0)
    #Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(LR_t, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)  
    #Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    LR_t = LogisticRegression(**best_params, random_state=0)
    LR_t.fit(X_train, y_train)
    #Predict the classes of the testing data
    y_pred = LR_t.predict(X_test)

    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("#######################################################################")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("#######################################################################")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return LR_t

  def GNB_t(self, X_train, y_train, y_test, X_test):
    # Create a Gaussian Naive Bayes object
    gnb = GaussianNB()

    # Define the hyperparameter grid to search over
    param_grid = {'var_smoothing': np.logspace(0,-9, num=100)}

    # Create a GridSearchCV object and fit it to the training data
    gnb = GridSearchCV(gnb, param_grid, cv=10, scoring='accuracy')
    gnb.fit(X_train, y_train)

    #  Predict the classes of the testing data using the best estimator found by GridSearchCV
    y_pred = gnb.best_estimator_.predict(X_test)

    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return gnb

  def DT_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid
    param_grid = {'max_depth': [3, 5, 7, None], 
                  'min_samples_split': [2, 5, 10],
                  'min_samples_leaf': [1, 2, 4]}

    # Create a decision tree object
    dt = DecisionTreeClassifier(random_state=0)
    # Create a GridSearchCV object with 5-fold cross-validation
    dt_cv = GridSearchCV(dt, param_grid, cv=5)

    # Train the model on the training data
    dt_cv.fit(X_train, y_train)
    # Print the best parameters and best score
    print('Best Parameters:', dt_cv.best_params_)
    print('Best Score:', dt_cv.best_score_)
    # Predict the classes of the testing data using the best model
    y_pred = dt_cv.predict(X_test)

    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return dt_cv

  def RF_t(self, X_train, y_train, y_test, X_test):
    # Set the parameter grid for hyperparameter tuning
    param_grid = {
        'n_estimators': [100, 200, 300],
        'max_depth': [None, 5, 10],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4],
        'max_features': ['auto', 'sqrt']
    }
    # Create a random forest classifier object
    rfc = RandomForestClassifier(random_state=0)
    # Create a GridSearchCV object
    grid_search = GridSearchCV(estimator=rfc, param_grid=param_grid, cv=5)
    # Train the GridSearchCV object on the training data
    grid_search.fit(X_train, y_train)
    # Print the best parameters and best score
    print("Best Parameters: ", grid_search.best_params_)
    print("Best Score: ", grid_search.best_score_)
    # Predict the classes of the testing data using the best estimator from the GridSearchCV
    y_pred = grid_search.best_estimator_.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return grid_search

  def SVC_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf', 'poly', 'sigmoid'], 'gamma': ['scale', 'auto']}
    # Create an SVM object
    svc = SVC(random_state=0)
    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(svc, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    svc = SVC(**best_params, probability=True, random_state=0)
    svc.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = svc.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return svc

  def KNN_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_neighbors': [3, 5, 7, 9, 11], 'weights': ['uniform', 'distance']}

    # Create a KNN object
    knn = KNeighborsClassifier()

    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(knn, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)

    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    knn = KNeighborsClassifier(**best_params)
    knn.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = knn.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return knn


  def GB_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_estimators': [50, 100, 150], 'max_depth': [3, 5, 7], 'learning_rate': [0.01, 0.1, 1.0]}
    # Create a Gradient Boosting object
    gb = GradientBoostingClassifier(random_state=0)
    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(gb, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    gb = GradientBoostingClassifier(**best_params, random_state=0)
    gb.fit(X_train, y_train)
    # Predict the classes of the testing data
    y_pred = gb.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)
    print("=======================================================================")
    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)
    print("=======================================================================")
    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return gb

  def ADAB_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_estimators': [50, 100, 150], 'learning_rate': [0.01, 0.1, 1.0]}
    # Create an AdaBoost object
    ada = AdaBoostClassifier(random_state=0)

    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(ada, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    ada = AdaBoostClassifier(**best_params, random_state=0)
    ada.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = ada.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return ada

  def BAG_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'n_estimators': [50, 100, 150], 'max_samples': [0.5, 0.7, 1.0], 'max_features': [0.5, 0.7, 1.0]}
    # Create a Bagging object
    tree = DecisionTreeClassifier(random_state=0)
    bag = BaggingClassifier(tree, random_state=0)
    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(bag, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    bag = BaggingClassifier(tree, **best_params, random_state=0)
    bag.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = bag.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return bag

  def XGB_t(self, X_train, y_train, y_test, X_test):
    param_grid = {'n_estimators': [50, 100, 150], 'learning_rate': [0.01, 0.1, 1.0], 'max_depth': [3, 5, 7]}
    xgb = XGBClassifier(random_state=0)
    grid_search = GridSearchCV(xgb, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    best_params = grid_search.best_params_
    xgb = XGBClassifier(**best_params, random_state=0)
    xgb.fit(X_train, y_train)
    y_pred = xgb.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return xgb

  def LGB_t(self, X_train, y_train, y_test, X_test):
    # Define the parameter grid for GridSearchCV
    param_grid = {'num_leaves': [31, 63, 127], 'learning_rate': [0.1, 0.05, 0.01], 'n_estimators': [50, 100, 150]}

    # Create a LightGBM object
    lgbm = lgb.LGBMClassifier(random_state=0)

    # Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(lgbm, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)
    # Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    lgbm = lgb.LGBMClassifier(**best_params, random_state=0)
    lgbm.fit(X_train, y_train)

    # Predict the classes of the testing data
    y_pred = lgbm.predict(X_test)
    # Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return lgbm

  def CB_t(self, X_train, y_train, y_test, X_test):
    #Define the parameter grid for GridSearchCV
    param_grid = {'learning_rate': [0.1, 0.05, 0.01], 'n_estimators': [50, 100, 150], 'depth': [4, 6, 8]}

    #Create a CatBoost object
    cat = CatBoostClassifier(random_state=0, verbose=0)
    #Perform GridSearchCV to find the best hyperparameters
    grid_search = GridSearchCV(cat, param_grid, scoring='accuracy', cv=5, n_jobs=-1)
    grid_search.fit(X_train, y_train)

    #Get the best hyperparameters and train the model on the training data
    best_params = grid_search.best_params_
    cat = CatBoostClassifier(**best_params, random_state=0, verbose=0)
    cat.fit(X_train, y_train)
    #Predict the classes of the testing data
    y_pred = cat.predict(X_test)

    #Evaluate the model performance
    acc = accuracy_score(y_test, y_pred)
    print('Accuracy:', acc)

    cm = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix:\n', cm)

    cr = classification_report(y_test, y_pred)
    print('Classification Report:\n', cr)

    return cat

  def LDA_t():
    print("LDA has no Parameter Tuning")

  def QDA_t():
    print("QDA has no parameter tuning")


In [7]:
modelt = Model_tuning()

#importing CSV 

In [8]:
df = pd.read_excel('/content/drive/MyDrive/Dashborad_academics/prediction_dataset1.xlsx')

In [9]:
df.head()

Sr. No.  AM-I(70442101)Attempts  AM-I(70442101) ESE (70) Final  \
0        1                       1                             32   
1        2                       1                             29   
2        3                       1                             64   
3        4                       1                             53   
4        5                       1                             31   

   AM-I(70442101) ISE (30) Final  AM-I(70442101) ICA (25) Final  \
0                             28                             23   
1                             25                             19   
2                             30                             24   
3                             25                             22   
4                             25                             24   

   AM-I(70442101) Condol/ Grace Final  AM-I(70442101) Total (125) Final  \
0                                   0                                83   
1                                   0                                73   
2                                   0                               118   
3                                   0                               100   
4                                   0                                80   

  AM-I(70442101)Grade Final  AM-I(70442101) GP Final  \
0                         A                        8   
1                        B+                        7   
2                         O                       10   
3                         O                       10   
4                         A                        8   

   AM-I(70442101) EGP (Credits = 4) Final  ... Sem VII & VIII BE SGPA Final    \
0                                      32  ...                       8.142857   
1                                      28  ...                       8.244898   
2                                      40  ...                       9.142857   
3                                      40  ...                       9.224490   
4                                      32  ...                       9.265306   

   Sem VII & VIII BE Status Final   Sem VII & VIII BE Grade Final  \
0                             Pass                              A   
1                             Pass                              A   
2                             Pass                             A+   
3                             Pass                             A+   
4                             Pass                             A+   

   Grand Total (5000)      %   EGP  CGPA (Credits = 153) Status  Grade  \
0                3309  66.18  1212                  7.92   Pass      A   
1                3426  68.52  1228                  8.03   Pass      A   
2                3909  78.18  1380                  9.02   Pass     A+   
3                4003  80.06  1430                  9.35   Pass     A+   
4                4011  80.22  1424                  9.31   Pass     A+   

   Number of extra years required  
0                               0  
1                               0  
2                               0  
3                               0  
4                               0  

[5 rows x 509 columns]

#Distrubuting data semester wise to get predictions and suggestions semester wise

In [10]:

#semester wise distribution
sem3 = df.iloc[:,1:75]
sem4 = df.iloc[:,75:149]
sem34 = df.iloc[:,149:157]
sem5 = df.iloc[:,157:239]
sem6 = df.iloc[:,239:327]
sem56 = df.iloc[:,327:335]
sem7 = df.iloc[:,335:418]
sem8 = df.iloc[:,418:494]
sem78 = df.iloc[:,494:502]
grandtotal = df.iloc[:,502:508]

#Distributing data subject wise to get predictions and suggestions subject wise

In [11]:
#subject wise distribution
am1 = df.iloc[:,1:11]
dms = df.iloc[:,11:21]
acc = df.iloc[:,21:34]
dt = df.iloc[:,34:47]
cg = df.iloc[:,47:57]
vb = df.iloc[:,57:66]
sem_3 = df.iloc[:,66:75]
am2 = df.iloc[:,75:85]
toc = df.iloc[:,85:95]
mp = df.iloc[:,95:108]
dc = df.iloc[:,108:118]
ds = df.iloc[:,118:131]
oodp = df.iloc[:,131:140]
sem_4 = df.iloc[:,140:157]
osc = df.iloc[:,157:170]
cn = df.iloc[:,170:183]
sp = df.iloc[:,183:193]
daa = df.iloc[:,193:203]
co = df.iloc[:,203:213]
jp = df.iloc[:,213:222]
sl1 = df.iloc[:,222:230]
sem_5 = df.iloc[:,230:239]
dbe = df.iloc[:,239:252]
cc = df.iloc[:,252:262]
uos = df.iloc[:,262:272]
mc = df.iloc[:,272:282]
se = df.iloc[:,282:292]
c = df.iloc[:,292:301]
mpj = df.iloc[:,301:310]
sl2 = df.iloc[:310:318]
sem_6 = df.iloc[:,318:335]
aca = df.iloc[:,335:345]
dsys = df.iloc[:,345:355]
mds = df.iloc[:,355:368]
pp1 = df.iloc[:,368:377]
py = df.iloc[:,377:383]
vt = df.iloc[:,383:389]
el1 = df.iloc[:,389:399]
el2 = df.iloc[:,399:409]
sem_7 = df.iloc[:,409:418]
mis = df.iloc[:,418:428]
ics = df.iloc[:,428:441]
wt = df.iloc[:,441:450]
pp2 = df.iloc[:,450:459]
ost = df.iloc[:,459:465]
el3 = df.iloc[:,465:475]
el4 = df.iloc[:,475:485]
sem_8 = df.iloc[:,485:502]

In [12]:
def preprocess(df,target):
  # Split the data into input features (X) and target variable (y)
  X = df.drop(target, axis=1)  # Input features
  y = df[target]  # Target variable
  # Convert the target variable to numeric values using label encoding
  le = LabelEncoder()
  y = le.fit_transform(y)
  cat_cols = X.select_dtypes(include=['category','object']).columns.tolist()

  print(cat_cols)
  # Convert categorical features into numerical values using one-hot encoding
  categorical_cols = cat_cols
  ohe = OneHotEncoder(handle_unknown='ignore', sparse=False)
  X_cat = pd.DataFrame(ohe.fit_transform(X[categorical_cols]))
  X_cat.columns = ohe.get_feature_names_out(categorical_cols)
  X_num = X.drop(categorical_cols, axis=1)
  X = pd.concat([X_num, X_cat], axis=1)
  # Split data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
  print("Shape of training split: ", X_train.shape)
  print("Shape of test split: ", X_test.shape)

  return X_train, X_test, y_train, y_test

#Grand Total


In [51]:
grandtotal.head()

Grand Total (5000)      %   EGP  CGPA (Credits = 153) Status Grade
0                3309  66.18  1212                  7.92   Pass     A
1                3426  68.52  1228                  8.03   Pass     A
2                3909  78.18  1380                  9.02   Pass    A+
3                4003  80.06  1430                  9.35   Pass    A+
4                4011  80.22  1424                  9.31   Pass    A+

In [14]:
grandtotal.shape

(200, 83)

In [52]:
target = 'Grade'

In [53]:
X_train, X_test, y_train, y_test = preprocess(grandtotal,target)

['Status']
Shape of training split:  (160, 5)
Shape of test split:  (40, 5)


#Logistic Regression

In [54]:
model.LR(X_train,y_train,y_test,X_test)

Accuracy: 0.925
Confusion Matrix:
 [[14  0  0]
 [ 3 21  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.88      0.93        24
           3       1.00      1.00      1.00         2

    accuracy                           0.93        40
   macro avg       0.94      0.96      0.95        40
weighted avg       0.94      0.93      0.93        40



Tuning and fitting

In [55]:
modelt.LR_t(X_train,y_train,y_test,X_test)

Accuracy: 0.925
#######################################################################
Confusion Matrix:
 [[14  0  0]
 [ 3 21  0]
 [ 0  0  2]]
#######################################################################
Classification Report:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.88      0.93        24
           3       1.00      1.00      1.00         2

    accuracy                           0.93        40
   macro avg       0.94      0.96      0.95        40
weighted avg       0.94      0.93      0.93        40



LogisticRegression(C=10.0, random_state=0)

#Gaussian Naive Bayes

In [56]:
model.GNB(X_train,y_train,y_test,X_test)

Accuracy: 0.925
Confusion Matrix:
 [[14  0  0]
 [ 3 21  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.88      0.93        24
           3       1.00      1.00      1.00         2

    accuracy                           0.93        40
   macro avg       0.94      0.96      0.95        40
weighted avg       0.94      0.93      0.93        40



GaussianNB()

Tuning and fitting

In [57]:
modelt.GNB_t(X_train,y_train,y_test,X_test)

Accuracy: 0.925
Confusion Matrix:
 [[14  0  0]
 [ 3 21  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.88      0.93        24
           3       1.00      1.00      1.00         2

    accuracy                           0.93        40
   macro avg       0.94      0.96      0.95        40
weighted avg       0.94      0.93      0.93        40



GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.3...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy')

#Decision Tree

In [58]:
model.DT(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [59]:
modelt.DT_t(X_train,y_train,y_test,X_test)

Best Parameters: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score: 1.0
Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'max_depth': [3, 5, 7, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

#Random Forest

In [60]:
model.RF(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



Tuning and Fitting

In [61]:
modelt.RF_t(X_train,y_train,y_test,X_test)

Best Parameters:  {'max_depth': None, 'max_features': 'auto', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}
Best Score:  0.99375
Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=0),
             param_grid={'max_depth': [None, 5, 10],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]})

#Support Vector Classifier

In [62]:
model.SVC(X_train,y_train,y_test,X_test)

Accuracy: 0.875
Confusion Matrix:
 [[14  0  0]
 [ 3 21  0]
 [ 0  2  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       0.91      0.88      0.89        24
           3       0.00      0.00      0.00         2

    accuracy                           0.88        40
   macro avg       0.58      0.62      0.60        40
weighted avg       0.84      0.88      0.85        40



Tuning and fitting

In [63]:
modelt.SVC_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



SVC(C=0.1, kernel='linear', probability=True, random_state=0)

#K - Nearrest Neighbours

In [64]:
model.KNN(X_train,y_train,y_test,X_test)

Accuracy: 0.925
Confusion Matrix:
 [[14  0  0]
 [ 3 21  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.88      0.93        24
           3       1.00      1.00      1.00         2

    accuracy                           0.93        40
   macro avg       0.94      0.96      0.95        40
weighted avg       0.94      0.93      0.93        40



Tuning and fitting

In [65]:
modelt.KNN_t(X_train,y_train,y_test,X_test)

Accuracy: 0.925
Confusion Matrix:
 [[14  0  0]
 [ 3 21  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.88      0.93        24
           3       1.00      1.00      1.00         2

    accuracy                           0.93        40
   macro avg       0.94      0.96      0.95        40
weighted avg       0.94      0.93      0.93        40



KNeighborsClassifier(n_neighbors=3)

#Gradient Boosting

In [66]:
model.GB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [67]:
modelt.GB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



GradientBoostingClassifier(learning_rate=1.0, n_estimators=50, random_state=0)

#AdaBoost

In [68]:
model.ADAB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [69]:
modelt.ADAB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



AdaBoostClassifier(random_state=0)

#Bagging

In [70]:
model.BAG(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [71]:
modelt.BAG_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



BaggingClassifier(estimator=DecisionTreeClassifier(random_state=0),
                  max_features=0.5, max_samples=0.5, n_estimators=150,
                  random_state=0)

#XGBoost

In [72]:
model.XGB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [73]:
modelt.XGB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=50, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

#LightGBM

In [74]:
model.LGB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [75]:
modelt.LGB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



LGBMClassifier(random_state=0)

#CATBoost

In [76]:
model.CB(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



tuning and fitting

In [77]:
modelt.CB_t(X_train,y_train,y_test,X_test)

Accuracy: 1.0
Confusion Matrix:
 [[14  0  0]
 [ 0 24  0]
 [ 0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         2

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



#Linear Discriminant Analysis

In [78]:
model.LDA(X_train,y_train,y_test,X_test)

Accuracy: 0.9
Confusion Matrix:
 [[13  0  1  0]
 [ 3 21  0  0]
 [ 0  0  0  0]
 [ 0  0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.93      0.87        14
           1       1.00      0.88      0.93        24
           2       0.00      0.00      0.00         0
           3       1.00      1.00      1.00         2

    accuracy                           0.90        40
   macro avg       0.70      0.70      0.70        40
weighted avg       0.93      0.90      0.91        40



LinearDiscriminantAnalysis()

#Quadratic discriminant Analysis

In [79]:
model.QDA(X_train,y_train,y_test,X_test)

Accuracy: 0.35
Confusion Matrix:
 [[14  0  0]
 [24  0  0]
 [ 2  0  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.35      1.00      0.52        14
           1       0.00      0.00      0.00        24
           3       0.00      0.00      0.00         2

    accuracy                           0.35        40
   macro avg       0.12      0.33      0.17        40
weighted avg       0.12      0.35      0.18        40



QuadraticDiscriminantAnalysis()

#========================================================